function passengerVehicleConfigWindow
% passengerVehicleConfigWindow Opens a simple UI with passenger car parameters
%   Run inside MATLAB to review or modify the default passenger vehicle values.

params = struct(...
    'includeTrailer', false, ...
    'tractorMass', 2500, ...
    'trailerMass', 0, ...
    'tractorLength', 4.5, ...
    'tractorWidth', 1.8, ...
    'tractorHeight', 1.4, ...
    'tractorCoGHeight', 0.5, ...
    'tractorWheelbase', 2.5, ...
    'tractorTrackWidth', 1.5, ...
    'numTiresPerAxleTractor', 2, ...
    'maxEngineTorque', 250, ...
    'torqueFileName', 'sedan_torque_curve.xlsx', ...
    'maxGear', 5, ...
    'gearRatios', [3.5 2.1 1.3 1.0 0.8], ...
    'finalDriveRatio', 2.8 ...
    );

f = uifigure('Name','Passenger Vehicle Configuration');
names = fieldnames(params);
values = struct2cell(params);
uitable(f,'Data',[names values], ...
    'ColumnName',{'Parameter','Value'}, ...
    'Position',[20 20 360 400]);
end
